version: 2

models:
  - name: agg_festival_country
    description: "Aggregated table for festival country"
    columns:
      - name: festival_country
        description: "The Festival Country"
        tests:
          - not_null